# Akash Network Service Description Language (SDL) File

version: '2.0'

services:
  app:
    image: supervirgo/demo2:latest
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    app:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          - size: 512Mi

placement:
  akash:
    pricing:
      app:
        denom: uakt
        amount: 3000

deployment:
  app:
    akash:
      profile: app
      count: 1
